import type {Metadata} from "next";

export const metadata:Metadata={title:"Terms & Conditions | A3 Group SG",description:"Booking, payment, cancellation and service terms for A3 Group SG limousine services."};

export default function TermsPage(){return <main className="termsPage">
  <header className="bookingHeader"><a className="logo" href="/"><b>A3</b><span><strong>A3 GROUP SG</strong><small>PRIVATE CHAUFFEUR</small></span></a><a href="/">← Back to website</a></header>
  <section className="termsHero"><p className="eyebrow">SERVICE POLICY</p><h1>Terms & Conditions</h1><p>These terms apply to limousine, airport transfer, hourly disposal, point-to-point and Singapore–Johor Bahru bookings made with A3 Group SG.</p><div className="termsMeta"><span>Version: 2026-07-29</span><span>Last updated: 29 July 2026</span></div></section>
  <div className="termsContent">
    <section className="termsNotice"><h2>Important booking notice</h2><p>All online bookings are requests and remain pending until availability and the final amount are confirmed by our team.</p></section>
    <section><h2>1. Booking lead time</h2><p>Bookings must be submitted at least six hours before pickup. Urgent bookings should be made by telephone or WhatsApp and remain subject to availability.</p></section>
    <section><h2>2. Rates and payment</h2><ul><li>Displayed prices are starting or base prices unless expressly stated otherwise.</li><li>ERP, parking, tolls, waiting time, additional stops, remote-area fees and other published surcharges may be added.</li><li>Payment instructions and any required deposit will be provided during confirmation.</li><li>A booking is confirmed only after our team issues confirmation and any required payment is received.</li></ul></section>
    <section><h2>3. Passenger and luggage capacity</h2><p>The customer must select a vehicle suitable for the declared passenger and luggage quantities. The driver may refuse unsafe overloading. A larger vehicle or additional vehicle may be required at extra cost.</p></section>
    <section><h2>4. Airport transfers and waiting time</h2><ul><li>Airport arrival bookings include up to 60 minutes of complimentary waiting from the confirmed landing time unless otherwise stated.</li><li>Other transfers include up to 15 minutes of complimentary waiting.</li><li>Additional waiting is chargeable at the published rate.</li><li>The customer is responsible for providing the correct flight number, terminal and arrival details.</li></ul></section>
    <section><h2>5. Hourly disposal</h2><p>Hourly disposal has a minimum booking of three hours. Extra time is billed in accordance with the published hourly rate. The itinerary must remain within the booked service area unless otherwise agreed.</p></section>
    <section><h2>6. Cross-border travel</h2><p>Singapore to Johor Bahru prices are quoted from the published starting price. Final pricing may vary according to destination, route, vehicle, waiting time, immigration conditions, multiple stops, tolls and timing. Passengers must hold valid travel documents and comply with immigration requirements.</p></section>
    <section><h2>7. Additional stops and itinerary changes</h2><p>Unplanned stops, detours, destination changes or route extensions may be refused when they affect another confirmed job and may incur additional charges.</p></section>
    <section><h2>8. Cancellation, refund and no-show</h2><p>Cancellation and refund eligibility depends on the notice period, vehicle arrangement and any third-party costs already incurred. Late cancellation and no-show bookings may be charged up to the full confirmed amount. Any specific cancellation terms stated in the booking confirmation take priority.</p></section>
    <section><h2>9. Child seats and accessibility requests</h2><p>Child seats, booster seats, wheelchair support and other special arrangements must be requested in advance and are subject to availability and published charges.</p></section>
    <section><h2>10. Conduct, cleaning and damage</h2><p>Smoking, illegal activity and unsafe conduct are prohibited. The customer is responsible for reasonable cleaning, repair or replacement costs arising from damage, excessive soiling or misuse caused by passengers.</p></section>
    <section><h2>11. Delays and vehicle substitution</h2><p>We will use reasonable efforts to provide the confirmed service. Traffic, weather, accidents, immigration queues and other events outside our control may cause delays. We may substitute an equivalent or higher-capacity vehicle where operationally necessary.</p></section>
    <section><h2>12. Liability</h2><p>To the extent permitted by law, liability is limited to direct loss reasonably arising from the booked transport service. We are not responsible for missed flights, appointments or consequential loss caused by inaccurate customer information or events outside our reasonable control.</p></section>
    <section><h2>13. Privacy and booking records</h2><p>Customer details are used to arrange, confirm and fulfil the transport service, communicate with the customer and maintain operational records. Booking submissions record acceptance of the applicable terms version and acceptance time.</p></section>
    <section><h2>14. Contact</h2><p>Questions about a booking or these terms may be sent through the contact and WhatsApp channels shown on this website.</p><a className="gold termsBack" href="/book">Return to booking</a></section>
  </div>
</main>}
