"use client";
import {FormEvent,useEffect,useState} from "react";

type Vehicle={vehicle_name:string};
export default function BookPage(){
 const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [startedAt]=useState(()=>Date.now());
 useEffect(()=>{const finance=(process.env.NEXT_PUBLIC_A3_FINANCE_URL||"https://finance.a3group.sg").replace(/\/$/,"");fetch(`${finance}/api/public/website-catalogue?site=limousine`,{cache:"no-store"}).then(r=>r.json()).then(p=>{const names=Array.from(new Set<string>((Array.isArray(p.items)?p.items:[]).map((x:any)=>String(x.title_en||x.service_name||"")).filter((name:string)=>Boolean(name))));setVehicles(names.map((vehicle_name:string)=>({vehicle_name}))) }).catch(()=>setVehicles([]))},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form.entries());try{const response=await fetch("/api/limousine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,started_at:startedAt,company:""})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to submit booking.");setMessage(`Booking submitted. Reference: ${result.reference}`);event.currentTarget.reset()}catch(error){setMessage(error instanceof Error?error.message:"Unable to submit booking.")}finally{setBusy(false)}}
 return <main className="standalone"><a className="back" href="/">← Back to website</a><section className="pageIntro"><p>ONLINE BOOKING</p><h1>Reserve your limousine journey.</h1><span>Your request is sent directly to A3 Finance as a pending booking for staff confirmation.</span></section><form className="publicForm" onSubmit={submit}><label>Service<select name="service" required defaultValue=""><option value="" disabled>Select service</option><option>Airport Transfer</option><option>Hourly Chauffeur</option><option>Point-to-Point</option><option>Singapore ↔ Johor</option><option>Wedding / Event</option></select></label><label>Vehicle<select name="vehicle" required defaultValue=""><option value="" disabled>Select vehicle</option>{vehicles.map(v=><option key={v.vehicle_name}>{v.vehicle_name}</option>)}</select></label><label>Pickup date<input type="date" name="date" required/></label><label>Pickup time<input type="time" name="time" required/></label><label className="full">Pickup location<input name="pickup" required/></label><label className="full">Destination / itinerary<textarea name="destination" required/></label><label>Passengers<input name="passengers" type="number" min="1" defaultValue="1"/></label><label>Luggage<input name="luggage" type="number" min="0" defaultValue="0"/></label><label>Flight number<input name="flight" placeholder="Optional"/></label><label>Airline<input name="airline" placeholder="Optional"/></label><label>Full name<input name="name" required/></label><label>Mobile / WhatsApp<input name="contact" required/></label><label className="full">Email<input name="email" type="email" placeholder="Optional"/></label><label className="full">Remarks<textarea name="remarks"/></label><button className="gold full" disabled={busy}>{busy?"Submitting…":"Submit Booking"}</button>{message&&<p className="formMessage full">{message}</p>}</form></main>
}
